# Generated by Django 4.2 on 2023-04-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='path',
            field=models.FileField(upload_to='files/'),
        ),
    ]
